// Generated by Modulux Coding IDE
// Board: Modulux ESP32-S3
#include <Arduino.h>


void setup() {
  Serial.begin(115200);
  { unsigned long _t=millis(); while(!Serial && millis()-_t<3000){delay(10);} }
  delay(150);

    Serial.print("SETUP OK");
}

void loop() {
    Serial.println("Hello World");
    delay(1000);
}